spring:
  datasource:
    url: jdbc:mysql://rm-m5eravyow76705i71eo.mysql.rds.aliyuncs.com:3306/my_test
    username: tqx
    password: 123456a!
    driver-class-name: com.mysql.jdbc.Driver
inspur:
  self-defined:
    user-name: dev-tqx
    username: 田庆新

#修改项目的端口号和上下文
server:
  port: 8089
  servlet:
    context-path: /app
