server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    \u662F\u5426\u83B7\u53D6\u5F53\u524D\u670D\u52A1\u7684\u4FE1\u606F
    fetch-registry: false
#    \u662F\u5426\u5C06\u81EA\u8EAB\u6CE8\u518C\u5230eureka
    register-with-eureka: false
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
#\u6CE8\u518C\u5230eureka\u6CE8\u518C\u4E2D\u5FC3\u7684service_id
spring:
  application:
    name: eureka-server